### ISSUE TITLE
[Bug] No characters showing up + error is thrown

### ISSUE THREAD

**Issue by soleilvermeil** [SoleilVermeil/court-of-fontaine#7]
**What happened?**
When I checked UID `702405924`, no characters were displayed on the page. On some cases, the page doesn't even load the following error appears:
```
Environment:


Request Method: GET
Request URL: http://192.168.3.100:8000/uid/702405924/

Django Version: 4.2.7
Python Version: 3.11.7
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'app',
 'debug_toolbar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/views.py", line 18, in inspect
    scripts.add_player(uid)
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/scripts.py", line 232, in add_player
    for roll_id in artifacts[artifact_index]['reliquary']['appendPropIdList']:
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: KeyError at /uid/702405924/
Exception Value: 'appendPropIdList'

```

**What was expected?**
Since the characters show up on [Enka](https://enka.network/u/702405924/), they should also show up here.

**Screenshots**
![image](https://github.com/SoleilVermeil/court-of-fontaine/assets/100100316/e1028686-ae12-47b2-8c13-1c0b7e67eac2)

**Comment by soleilvermeil** [comment]
Fixed with 7ec9c20d04f721f7953d7a39afa006c119f5e913.
